version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:7dc20d44ab5b2cc2498c02b0df3301e3f6d0eec4
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml