version: '3.4'

services:
    eventstore.db:
        image: eventstore/eventstore
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - "1113:1113"
            - "2113:2113"
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore
    keycloak-postgres:
        image: postgres
        environment:
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=keycloak
            - POSTGRES_DB=keycloak
        volumes:
            - type: volume
              source: keycloak-postgres-data
              target: /var/lib/postgresql/data/
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=keycloak-postgres
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_SCHEMA=public
            - DB_PASSWORD=keycloak
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=Pa55w0rd
        ports:
            - 8080:8080
        depends_on:
            - keycloak-postgres
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=andrew.leichter@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
            - PGADMIN_LISTEN_PORT=8081
        ports:
            - 8082:8081
        volumes:
            - type: volume
              source: pgadmin-data
              target: /var/lib/pgadmin
volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    keycloak-postgres-data:
    pgadmin-data:
