---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: docker.io/aleichter/portfolio-service
          env:
            - name: PORT
              value: "5001"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5001